name: Build & Tests

on:
  workflow_dispatch:

env:
  GO_VERSION: '1.17'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "my secret is ${{ secrets.JSON }}"
        toto=`echo '{}' | jq '. +  {"helloe":"toto"}'`
        toto=`echo $toto | jq '. + {"helloe2":"toto2"}'`
        echo $toto
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}
    - name: Download modules
      run: go mod download
    - name: Build project
      run: go build ./cmd/demo
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}
    - name: Linter
      uses: golangci/golangci-lint-action@v2
      with:
        version: latest
  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}
    - name: Go tests
      run: go test -v -race -coverprofile=coverage.out -covermode=atomic ./...
    - name: Upload coverage to Codecov
      run: bash <(curl -s https://codecov.io/bash) -C $(Build.SourceVersion)
    - name: Upload coverage
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: coverage.out
  analysis:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download coverage
      uses: actions/download-artifact@v2
      with:
        name: coverage
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
        SONAR_HOST_URL: http://demosonar.westeurope.cloudapp.azure.com:9000/
      with:
        args: >
          -Dsonar.projectKey=demo.github.actions
          -Dsonar.go.coverage.reportPaths=coverage.out
          -Dsonar.sources=.
          -Dsonar.verbose=true
          -Dsonar.exclusions=**/*_test.go
