name: Docker

on: push
# on:
#   push:
#     branches: [ master ]

env:
  GO_VERSION: '1.17'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push to registry
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: atincelin/demo:latest
