name: Quality Checks

on: push

env:
  GO_VERSION: '1.17'

jobs:
  runs-on: ubuntu-latest
  lint:
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Linter
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
  sonar:
    name: SonarQube
    steps:
      - uses: philips-software/sonar-scanner-action@v1.3.0
        with:
          token: ${{ secrets.SONARQUBE_TOKEN }}
          projectName: Github Actions Demo
          projectKey: demo.github.actions
          url: https://demosonar.westeurope.cloudapp.azure.com
          isCommunityEdition: true
